#!/usr/bin/env python3
"""
Interactive setup for gamesync.

  python install.py

Prompts for your settings, writes .env, installs dependencies, registers the
background watcher as a logon scheduled task, and (optionally) starts it now.
Safe to re-run; it overwrites .env and re-registers the task.
"""

import os
import sys
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(HERE, ".env")
SCRIPT = os.path.join(HERE, "gamesync.py")
TASK_NAME = "GameSync"


def ask(prompt, default=""):
    suffix = f" [{default}]" if default else ""
    val = input(f"{prompt}{suffix}: ").strip()
    return val or default


def ask_yes(prompt, default=True):
    d = "Y/n" if default else "y/N"
    val = input(f"{prompt} ({d}): ").strip().lower()
    if not val:
        return default
    return val in ("y", "yes")


def detect_steam_path():
    try:
        import winreg
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\Valve\Steam") as k:
            p, _ = winreg.QueryValueEx(k, "SteamPath")
            if p and os.path.isdir(p):
                return os.path.normpath(p)
    except (OSError, ImportError):
        pass
    for guess in (r"C:\Program Files (x86)\Steam", r"C:\Program Files\Steam"):
        if os.path.isdir(guess):
            return guess
    return ""


def pythonw_path():
    cand = os.path.join(os.path.dirname(sys.executable), "pythonw.exe")
    return cand if os.path.isfile(cand) else sys.executable


def main():
    print("=" * 60)
    print(" gamesync setup")
    print("=" * 60)

    # 1. read existing .env values as defaults if present
    existing = {}
    if os.path.isfile(ENV_PATH):
        for line in open(ENV_PATH, encoding="utf-8"):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()

    print("\nWhich folders should be watched for games? (comma-separated)")
    games = ask("  GAMES_DIRS", existing.get("GAMES_DIRS", r"C:\Games"))

    print("\nSteamGridDB API key (https://www.steamgriddb.com/profile/preferences).")
    print("Required for artwork; leave blank to skip artwork.")
    key = ask("  STEAMGRIDDB_KEY", existing.get("STEAMGRIDDB_KEY", ""))

    print("\nPath to steamgrid.exe (https://github.com/boppreh/steamgrid/releases).")
    sg = ask("  STEAMGRID_EXE", existing.get("STEAMGRID_EXE", ""))
    if sg and not os.path.isfile(sg):
        print(f"  ! warning: {sg} not found (you can fix this later in .env)")

    steam = detect_steam_path()
    print(f"\nSteam install detected: {steam or '(not found)'}")
    steam = ask("  STEAM_PATH (blank = auto-detect)", existing.get("STEAM_PATH", ""))

    notif = ask_yes("\nShow desktop toast notifications when games are added?",
                    default=str(existing.get("NOTIFICATIONS", "false")).lower() == "true")

    print("\nAlso add games as Apollo/Vibepollo streaming tiles? (optional)")
    print("Safe to leave on - it does nothing if Apollo isn't installed.")
    apollo = ask_yes("  APOLLO_SYNC",
                     default=str(existing.get("APOLLO_SYNC", "true")).lower() == "true")
    apollo_apps = existing.get("APOLLO_APPS", "")
    apollo_url = existing.get("APOLLO_URL", "https://localhost:47990")
    apollo_token = existing.get("APOLLO_REORDER_TOKEN", "")
    if apollo:
        print("\n  Path to Apollo apps.json (blank = auto-detect).")
        apollo_apps = ask("  APOLLO_APPS", apollo_apps)
        print("\n  Scoped API token for no-restart reloads (blank = reload manually).")
        print("  Create one in the Apollo web UI, scoped to POST /api/apps/reorder.")
        apollo_token = ask("  APOLLO_REORDER_TOKEN", apollo_token)

    # 2. write .env (preserve template tuning keys)
    env = {
        "GAMES_DIRS": games,
        "STEAMGRIDDB_KEY": key,
        "STEAMGRID_EXE": sg,
        "STEAM_PATH": steam,
        "USERDATA_ID": existing.get("USERDATA_ID", "auto"),
        "STEAM_TAG": existing.get("STEAM_TAG", "GameSync"),
        "NOTIFICATIONS": "true" if notif else "false",
        "RESTART_STEAM_WHEN_IDLE": existing.get("RESTART_STEAM_WHEN_IDLE", "true"),
        "DEBOUNCE_SECONDS": existing.get("DEBOUNCE_SECONDS", "45"),
        "PERIODIC_CHECK_MINUTES": existing.get("PERIODIC_CHECK_MINUTES", "3"),
        "STEAMGRID_TIMEOUT_SECONDS": existing.get("STEAMGRID_TIMEOUT_SECONDS", "300"),
        "SKIP_FOLDERS": existing.get("SKIP_FOLDERS", "_CommonRedist,.claude"),
        "APOLLO_SYNC": "true" if apollo else "false",
        "APOLLO_APPS": apollo_apps,
        "APOLLO_URL": apollo_url,
        "APOLLO_REORDER_TOKEN": apollo_token,
    }
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write("# gamesync config - generated by install.py. Do NOT commit.\n")
        for k, v in env.items():
            f.write(f"{k}={v}\n")
    print(f"\nWrote {ENV_PATH}")

    # 3. install dependencies
    if ask_yes("\nInstall Python dependencies now (pip install -r requirements.txt)?"):
        subprocess.run([sys.executable, "-m", "pip", "install", "-r",
                        os.path.join(HERE, "requirements.txt")])

    # 4. register scheduled task
    if ask_yes(f"\nRegister the '{TASK_NAME}' watcher to start at logon?"):
        pyw = pythonw_path()
        tr = f'"{pyw}" "{SCRIPT}" --watch'
        res = subprocess.run(
            ["schtasks", "/Create", "/TN", TASK_NAME, "/TR", tr,
             "/SC", "ONLOGON", "/F", "/RL", "LIMITED"],
            capture_output=True, text=True,
        )
        print(res.stdout.strip() or res.stderr.strip())

    # 5. run once + start watcher
    if ask_yes("\nRun an initial sync now?"):
        subprocess.run([sys.executable, SCRIPT, "--once"])

    if ask_yes("\nStart the background watcher now (hidden)?"):
        pyw = pythonw_path()
        flags = 0
        if os.name == "nt":
            flags = subprocess.CREATE_NO_WINDOW | 0x00000008  # DETACHED_PROCESS
        subprocess.Popen([pyw, SCRIPT, "--watch"], creationflags=flags, close_fds=True)
        print("Watcher started.")

    print("\nDone. Edit .env any time; the watcher reloads it on restart.")
    print("Useful: python gamesync.py --status  |  --once --dry-run  |  --art")


if __name__ == "__main__":
    main()
